### ISSUE TITLE
Wrong country select data

### ISSUE THREAD

**Issue by samturner3** [charhagelin/weather_app#4]
![screen shot 2017-02-24 at 12 24 04 am](https://cloud.githubusercontent.com/assets/14887388/23260788/9e7f2706-fa27-11e6-9b07-2427776bf26f.png)
Ill have to fix it so it checks the correct data from the hash

**Comment by charhagelin** [comment]
fixed. changes made in ./current_location
from [2] to [3] in array for country short name.
```if hash[0][:address_components][3][:short_name] == "AU" ```
